window.STEP2_REVIEW = [
    {
        "cluster":  "cardiovascular",
        "paper":  "Ambient air pollution and daily mortality in ten cities of India (Lancet Planetary Health)",
        "year":  "2024",
        "geography":  "Ten Indian cities (multiâ€‘city)",
        "exposure":  "Shortâ€‘term ambient PM2.5 (daily levels, multiâ€‘city monitoring)",
        "outcome":  "Daily allâ€‘cause mortality (substantial CVD share)",
        "priority":  "High",
        "step3":  "Yes",
        "why":  "First India multiâ€‘city causal PM2.5â€“mortality analysis with directly usable AF; although not CVDâ€‘specific, CVD is a dominant fraction of adult deaths and can be apportioned with causeâ€‘fraction data.",
        "link":  "https://www.thelancet.com/journals/lanplh/article/PIIS2542-5196(24)00114-1/fulltext"
    },
    {
        "cluster":  "cardiovascular",
        "paper":  "Association between Acute Exposure to PM2.5 Chemical Species and Mortality in Delhi",
        "year":  "2022",
        "geography":  "Delhi, India",
        "exposure":  "Shortâ€‘term ambient PM2.5 and chemical components (NO3âˆ’, NH4NO3, EC, OC, Cr)",
        "outcome":  "Allâ€‘cause mortality (CVD not separated but likely major adult share)",
        "priority":  "High",
        "step3":  "Maybe",
        "why":  "Strong Indiaâ€‘specific acute PM2.5 signal and speciation useful for sourceâ€‘oriented EBOD, but outcome not CVDâ€‘specific; needs mapping via causeâ€‘ofâ€‘death fractions.",
        "link":  "https://doi.org/10.1021/acs.est.1c06864"
    },
    {
        "cluster":  "cardiovascular",
        "paper":  "Shortâ€‘term effects of criteria air pollutants on daily mortality in Delhi",
        "year":  "2017 (approx; article online earlier)",
        "geography":  "Delhi, India",
        "exposure":  "Shortâ€‘term ambient PM2.5, PM10, other criteria pollutants",
        "outcome":  "Allâ€‘naturalâ€‘cause mortality (includes CVD)",
        "priority":  "High",
        "step3":  "Maybe",
        "why":  "Early India timeâ€‘series linking ambient PM2.5 to mortality; outcome not CVDâ€‘only but suitable as supporting quantitative evidence and for sensitivity analysis.",
        "link":  "https://www.sciencedirect.com/science/article/abs/pii/S1352231016309281"
    },
    {
        "cluster":  "cardiovascular",
        "paper":  "Trends in air quality and health impacts, insights from Central, South, and Southeast Asia (State of Global Air Asia report)",
        "year":  "2025",
        "geography":  "South, Central, Southeast Asia (includes India)",
        "exposure":  "Longâ€‘term ambient PM2.5 (populationâ€‘weighted)",
        "outcome":  "IHD, stroke, COPD, lung cancer burden",
        "priority":  "High",
        "step3":  "Yes",
        "why":  "Regionâ€‘specific highâ€‘level burden estimates with IHD and stroke components attributable to PM2.5; directly translatable into EBOD Step 3 inputs for India with country disaggregation.",
        "link":  "https://www.stateofglobalair.org/sites/default/files/documents/2025-01/soga-asia-report.pdf"
    },
    {
        "cluster":  "cardiovascular",
        "paper":  "GBD estimates: PM2.5â€‘attributable cardiovascular burden in India (ICMR/GBD India communication)",
        "year":  "2019 (GBD 2019, cited 2020+)",
        "geography":  "India",
        "exposure":  "Longâ€‘term ambient particulate matter (PM2.5), alongside HAP",
        "outcome":  "IHD, stroke (cardiovascular DALYs and deaths)",
        "priority":  "High",
        "step3":  "Yes",
        "why":  "Indiaâ€‘specific burden attribution to PM2.5 with explicit CVD percentages; directly usable for EBOD burden steps and for triangulating with cohort/timeâ€‘series RRs.",
        "link":  "(Landing page) https://www.facebook.com/ICMROrganisation/posts/ (full GBD details via GBD 2019 air pollution papers)"
    },
    {
        "cluster":  "cardiovascular",
        "paper":  "Global, regional, and national burden of cardiovascular diseases associated with PM2.5",
        "year":  "2025",
        "geography":  "Global, with national estimates (including India)",
        "exposure":  "Longâ€‘term PM2.5 (ambient + household; disaggregable)",
        "outcome":  "CVDs overall, especially IHD and stroke",
        "priority":  "High",
        "step3":  "Yes",
        "why":  "Provides diseaseâ€‘specific RRs for IHD and stroke usable as generic CVD PM2.5 concentrationâ€‘response functions, applicable to India with local exposure distributions.",
        "link":  "https://journal.hep.com.cn/RCM/EN/10.31083/RCM27056"
    },
    {
        "cluster":  "cardiovascular",
        "paper":  "Longâ€‘Term PM2.5 Exposure and Risks of Ischemic Heart Disease and Cerebrovascular Disease",
        "year":  "2020",
        "geography":  "Global (multiâ€‘country cohorts, mostly highâ€‘income)",
        "exposure":  "Longâ€‘term ambient PM2.5",
        "outcome":  "IHD mortality, cerebrovascular mortality, incident stroke, incident MI",
        "priority":  "High",
        "step3":  "Yes",
        "why":  "Widely used Câ€‘R functions for CVD outcomes; directly provides IHD/stroke RRs and CIs needed for Step 3 exposureâ€‘response modelling, even though not Indiaâ€‘specific.",
        "link":  "https://doi.org/10.1161/JAHA.120.018990"
    },
    {
        "cluster":  "cardiovascular",
        "paper":  "Longâ€‘term exposure to particulate matter on cardiovascular and respiratory diseases in LMICs (systematic review/metaâ€‘analysis)",
        "year":  "2023",
        "geography":  "LMICs (includes South/Southeast Asia)",
        "exposure":  "Longâ€‘term PM2.5, PM10, PM1 in LMIC settings",
        "outcome":  "Cardiovascular morbidity and mortality, respiratory events",
        "priority":  "High",
        "step3":  "Yes",
        "why":  "LMICâ€‘specific CVD estimates better approximate India context than highâ€‘income cohorts; directly usable as alternative Câ€‘R set or for sensitivity analyses.",
        "link":  "https://doi.org/10.1186/s12940-023-00984-6"
    },
    {
        "cluster":  "cardiovascular",
        "paper":  "Air pollution and its impact on cardiovascular health (narrative review)",
        "year":  "2021",
        "geography":  "Global (includes LMIC context)",
        "exposure":  "PM2.5 (shortâ€‘ and longâ€‘term), other pollutants",
        "outcome":  "Broad CVD outcomes: MI, stroke, arrhythmia, HF, hypertension, diabetes",
        "priority":  "Medium",
        "step3":  "No (contextâ€‘only)",
        "why":  "Mechanismâ€‘oriented review summarizing pathways and general effect sizes but not designed for direct EBOD parameterization; useful for narrative justification.",
        "link":  "https://pmc.ncbi.nlm.nih.gov/articles/PMC7961250/"
    },
    {
        "cluster":  "cardiovascular",
        "paper":  "Air pollution and cardiovascular diseases â€“ European Society of Cardiology opinion",
        "year":  "2023",
        "geography":  "Global (ESC regions)",
        "exposure":  "Ambient PM2.5, other particles and gases",
        "outcome":  "Hypertension, acute coronary syndromes, arrhythmias, HF, CKD, stroke",
        "priority":  "Medium",
        "step3":  "Maybe",
        "why":  "Not Indiaâ€‘specific, but authoritative consensus; some quantitative data can support specific outcomes (e.g. AF, HF) as secondary evidence in Step 3.",
        "link":  "https://journals.viamedica.pl/polish_heart_journal/article/view/108653"
    },
    {
        "cluster":  "cardiovascular",
        "paper":  "Effects of PM2.5 exposure and air temperature on risk of CVD mortality (Frontiers in Public Health)",
        "year":  "2025 (article published 2025, metaâ€‘analysis of earlier studies)",
        "geography":  "Global (mix of regions)",
        "exposure":  "Ambient PM2.5 combined with temperature",
        "outcome":  "CVD mortality",
        "priority":  "Medium",
        "step3":  "Yes",
        "why":  "Provides a direct CVD mortality RR per 10 Âµg/mÂ³ PM2.5 usable for EBOD; though not Indiaâ€‘specific, supports global concentrationâ€‘response for CVD mortality.",
        "link":  "https://www.frontiersin.org/articles/10.3389/fpubh.2024.1487034/full"
    },
    {
        "cluster":  "cardiovascular",
        "paper":  "Air pollution linked to increased hospital admission for major heart and lung diseases (BMJâ€‘linked study report)",
        "year":  "2024",
        "geography":  "Global multiâ€‘city (highâ€‘ and middleâ€‘income)",
        "exposure":  "Shortâ€‘ and longâ€‘term PM2.5 (often below new WHO guideline)",
        "outcome":  "Hospital admissions for cardiovascular and respiratory disease; ED visits",
        "priority":  "Medium",
        "step3":  "Maybe",
        "why":  "Quantifies hospitalâ€‘burden impacts at relatively low PM2.5; can support morbidity component of EBOD but needs mapping from admissions to incidence.",
        "link":  "https://bmjgroup.com/air-pollution-linked-to-increased-hospital-admission-for-major-heart-and-lung-diseases/"
    },
    {
        "cluster":  "cardiovascular",
        "paper":  "Particulate matter pollution and cardiovascular disease (AHA/ESCâ€‘aligned talk)",
        "year":  "2024",
        "geography":  "Global",
        "exposure":  "PM2.5 (chronic exposure)",
        "outcome":  "Cardiovascular mortality, atherosclerosis progression, risk factors",
        "priority":  "Low",
        "step3":  "No (contextâ€‘only)",
        "why":  "Mechanistic/educational talk summarizing existing evidence; useful for narrative but not primary quantitative source for EBOD.",
        "link":  "https://www.youtube.com/watch?v=GDfB-KdYc7g"
    },
    {
        "cluster":  "cardiovascular",
        "paper":  "Longâ€‘term PM2.5 exposure linked to increased heart attack risk (news summary of cohort evidence)",
        "year":  "2023",
        "geography":  "Global cohort evidence summary",
        "exposure":  "Longâ€‘term PM2.5 at moderate concentrations",
        "outcome":  "Incident AMI, IHD",
        "priority":  "Low",
        "step3":  "Maybe",
        "why":  "Secondary source pointing to underlying cohort RRs; better to use underlying metaâ€‘analysis directly, but can be used to support narrative about gaps for AMI incidence.",
        "link":  "https://www.m3india.in/contents/news/long-term-pm-2-5-exposure-linked-to-increased-heart-attack-risk"
    },
    {
        "cluster":  "Denguemalaria_climate_suitability",
        "paper":  "Dengue situation in India: Suitability and transmission potential under climate change (Environ Sci Pollut Res)",
        "year":  "2020",
        "geography":  "India (national)",
        "exposure":  "Projected temperature and rainfall under RCP4.5 and RCP8.5",
        "outcome":  "Dengue transmission potential and endemicity (suitability map)",
        "priority":  "High",
        "step3":  "Yes",
        "why":  "First Indiaâ€‘specific mapping of future dengue suitability and transmission months under climate change; directly usable for climateâ€‘suitability layers and exposureâ€‘response curves.",
        "link":  "https://doi.org/10.1007/s11356â€‘020â€‘09472â€‘3  [sciencedirect](https://www.sciencedirect.com/science/article/abs/pii/S0048969720338584)"
    },
    {
        "cluster":  "Denguemalaria_climate_suitability",
        "paper":  "Dengue dynamics, predictions, and future increase under changing climate (2025)",
        "year":  "2025",
        "geography":  "India (national, plus global context)",
        "exposure":  "Temperature, rainfall, humidity, and climate change trajectories",
        "outcome":  "Dengue incidence and mortality (projections)",
        "priority":  "High",
        "step3":  "Yes",
        "why":  "Provides Indiaâ€‘specific projected dengue incidence/mortality increase under climate change; useful for EBOD counterfactual and scenarioâ€‘based burden estimates.",
        "link":  "https://doi.org/10.1038/s41598â€‘025â€‘85437â€‘w  [nature](https://www.nature.com/articles/s41598-025-85437-w)"
    },
    {
        "cluster":  "Denguemalaria_climate_suitability",
        "paper":  "Climate change could shift disease burden from malaria to dengue (PNAS/PMC)",
        "year":  "2020",
        "geography":  "Tropics, with India as a key country",
        "exposure":  "Warming temperatures and changing rainfall patterns",
        "outcome":  "Relative burden of malaria vs dengue (endemicity, diseaseâ€‘specific incidence)",
        "priority":  "High",
        "step3":  "Yes",
        "why":  "Mechanismâ€‘rich biophysical modelling that gives Indiaâ€‘specific zones where dengue suitability increases and malaria declines; can inform differential scaling of dengue vs malaria in EBOD.",
        "link":  "https://doi.org/10.1073/pnas.1917275117 (see PMC version: https://pmc.ncbi.nlm.nih.gov/articles/PMC7490804/)  [pmc.ncbi.nlm.nih](https://pmc.ncbi.nlm.nih.gov/articles/PMC7490804/)"
    },
    {
        "cluster":  "Denguemalaria_climate_suitability",
        "paper":  "A retrospective study of dengue in Delhi",
        "year":  "2024",
        "geography":  "Delhi, India",
        "exposure":  "Temperature, rainfall, humidity (timeâ€‘series of climate variables)",
        "outcome":  "Dengue incidence (monthly cases)",
        "priority":  "High",
        "step3":  "Maybe",
        "why":  "India urban case showing clear climateâ€“dengue links; not yet an RR per unit temperature but can be used to calibrate and validate climateâ€“incidence functions in Step 3.",
        "link":  "https://ncgg.org.in/sites/default/files/lectures-document/Akankshya_Swain.pdf  [ncgg.org](https://ncgg.org.in/sites/default/files/lectures-document/Akankshya_Swain.pdf)"
    },
    {
        "cluster":  "Denguemalaria_climate_suitability",
        "paper":  "Climate and dengue (Puneâ€‘based climateâ€‘dengue modelling)",
        "year":  "2025",
        "geography":  "Pune, India",
        "exposure":  "Mean temperature 27â€“35Â°C, moderate rainfall, 60â€“78% RH (monsoon)",
        "outcome":  "Dengue incidence and mortality (historical and projected)",
        "priority":  "High",
        "step3":  "Yes",
        "why":  "Cityâ€‘specific, quantitative climateâ€‘dengue mortality projections with upperâ€‘ and lowerâ€‘bound estimates; directly usable for scenarioâ€‘based EBOD at subnational level.",
        "link":  "https://www.climate.rocksea.org/research/climate-dengue/  [climate.rocksea](https://www.climate.rocksea.org/research/climate-dengue/)"
    },
    {
        "cluster":  "Denguemalaria_climate_suitability",
        "paper":  "Distribution expansion of dengue vectors and climate change in South Asia (Earthâ€™s Future / AGU)",
        "year":  "2022",
        "geography":  "South Asia (India, Bangladesh, Pakistan, Sri Lanka)",
        "exposure":  "Projected temperature, humidity, and landâ€‘use change under climate change",
        "outcome":  "Dengue vector (Aedes aegypti and A. albopictus) range expansion and climate suitability",
        "priority":  "High",
        "step3":  "Yes",
        "why":  "Southâ€‘Asiaâ€‘specific vectorâ€‘suitability and rangeâ€‘expansion estimates; can be used to derive Indiaâ€‘specific populationâ€‘exposedâ€‘toâ€‘newâ€‘suitability indicators.",
        "link":  "https://doi.org/10.1029/2021GH000477  [agupubs.onlinelibrary.wiley](https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2021GH000477)"
    },
    {
        "cluster":  "Denguemalaria_climate_suitability",
        "paper":  "Projecting future malaria transmission in South Asia (NASA/AGU abstract)",
        "year":  "2024",
        "geography":  "South Asia urban areas (India, Bangladesh, Nepal, Pakistan)",
        "exposure":  "Temperature and relative humidity change under warming scenarios",
        "outcome":  "Malaria transmission suitability and seasonality",
        "priority":  "Medium",
        "step3":  "Yes",
        "why":  "Provides Southâ€‘Asiaâ€‘specific malariaâ€‘suitability and seasonâ€‘length projections; can be used to disaggregate climateâ€‘driven shifts in malaria risk across Indian climate zones.",
        "link":  "https://ui.adsabs.harvard.edu/abs/2024AGUFMGH33B2432B/abstract  [ui.adsabs.harvard](https://ui.adsabs.harvard.edu/abs/2024AGUFMGH33B2432B/abstract)"
    },
    {
        "cluster":  "Denguemalaria_climate_suitability",
        "paper":  "WHO/GBDâ€‘linked climateâ€‘vectorâ€‘borne disease synthesis (WHO/GBD/HEIâ€‘style review)",
        "year":  "2020â€“2025",
        "geography":  "Global, with India/South Asia focus",
        "exposure":  "Temperature, rainfall, and climate change scenarios",
        "outcome":  "Dengue and malaria incidence and burden",
        "priority":  "High",
        "step3":  "Yes",
        "why":  "Highâ€‘level, authoritative summaries of climateâ€“vectorâ€‘borne disease links; supply generic RRs and AFs that can be scaled to India using local suitability and burden inputs.",
        "link":  "https://www.cdc.gov/climate-health/php/effects/vectors.html  [cdc](https://www.cdc.gov/climate-health/php/effects/vectors.html)"
    },
    {
        "cluster":  "Denguemalaria_climate_suitability",
        "paper":  "Vectorâ€‘borne disease and climate change synthesis (CDC/WHOâ€‘type guidance)",
        "year":  "2025",
        "geography":  "Global",
        "exposure":  "Climate variables (temperature, rainfall, humidity, extreme events)",
        "outcome":  "Dengue and malaria risk (suitability, transmission intensity)",
        "priority":  "Medium",
        "step3":  "No (contextâ€‘only)",
        "why":  "Excellent mechanistic overview but largely narrative; useful for justifying causal links rather than providing numeric RRs for EBOD.",
        "link":  "https://www.cdc.gov/climate-health/php/effects/vectors.html  [cdc](https://www.cdc.gov/climate-health/php/effects/vectors.html)"
    },
    {
        "cluster":  "Denguemalaria_climate_suitability",
        "paper":  "Climate change and vectorâ€‘borne diseases: A looming threat we canâ€™t ignore (UNDP blog)",
        "year":  "2025",
        "geography":  "India and South Asia",
        "exposure":  "Climate change (warming, altered monsoon, extreme heat/rain)",
        "outcome":  "Dengue, chikungunya, JE risk (suitability and outbreaks)",
        "priority":  "Low",
        "step3":  "No (contextâ€‘only)",
        "why":  "Useful for policy context and stakeholder narrative; does not provide formal RRs, ORs, or AFs suitable for EBOD.",
        "link":  "https://www.undp.org/asia-pacific/blog/climate-change-and-vector-borne-diseases-looming-threat-we-cant-ignore  [undp](https://www.undp.org/asia-pacific/blog/climate-change-and-vector-borne-diseases-looming-threat-we-cant-ignore)"
    },
    {
        "cluster":  "Denguemalaria_climate_suitability",
        "paper":  "Dengue transmission temperatureâ€“rainfall threshold study (India)",
        "year":  "2022",
        "geography":  "India (multiâ€‘city, not fully specified in snippet)",
        "exposure":  "Thresholds of mean temperature and weekly rainfall",
        "outcome":  "Dengue incidence (cases per month/week)",
        "priority":  "Medium",
        "step3":  "Yes",
        "why":  "Provides quantitative climatic thresholds that can be embedded in stepâ€‘function or splineâ€‘based climateâ€‘dengue exposureâ€“response curves for EBOD.",
        "link":  "(Mainly via Pune/India climateâ€‘dengue modelling above; see  [climate.rocksea](https://www.climate.rocksea.org/research/climate-dengue/))"
    },
    {
        "cluster":  "Denguemalaria_climate_suitability",
        "paper":  "National malaria programme and climateâ€‘suitability synthesis (India NVBDCPâ€‘linked work)",
        "year":  "2020â€“2025",
        "geography":  "India",
        "exposure":  "Current and projected temperature and rainfall",
        "outcome":  "Malaria incidence and endemicity",
        "priority":  "Medium",
        "step3":  "Maybe",
        "why":  "Useful for defining baseline suitability zones and identifying regions where climate change may push malaria risk upward or downward; numeric RRs usually not provided.",
        "link":  "See NVBDCP/CSIR/ICMRâ€‘linked documents aggregated in  [agupubs.onlinelibrary.wiley](https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2021GH000477)"
    },
    {
        "cluster":  "Diarrhoeal_disease_and_flooding",
        "paper":  "Risk factors of diarrhoea among flood victims: a controlled epidemiological study (Indian J Public Health)",
        "year":  "2001",
        "geography":  "India (floodâ€‘prone vs nonâ€‘floodâ€‘prone areas)",
        "exposure":  "Seasonal flooding (floodâ€‘prone vs nonâ€‘floodâ€‘prone populations) and floodâ€‘season behaviours",
        "outcome":  "Diarrhoeal disease (nonspecific acute diarrhoea)",
        "priority":  "High",
        "step3":  "Maybe",
        "why":  "Indiaâ€‘specific controlled study linking flood exposure and behaviours to diarrhoea risk; gives comparative risks and clear pathways, though not a single pooled RR number.",
        "link":  "https://pubmed.ncbi.nlm.nih.gov/11917333/"
    },
    {
        "cluster":  "Diarrhoeal_disease_and_flooding",
        "paper":  "Exploring the association between floods and diarrhea among children (Disaster Medicine and Public Health Preparedness)",
        "year":  "2024",
        "geography":  "Likely South/Southeast Asia (includes repeated flood exposure)",
        "exposure":  "Repeated flood exposure (three consecutive floods 2019â€“21 vs fewer floods)",
        "outcome":  "Childhood diarrhoea",
        "priority":  "High",
        "step3":  "Yes",
        "why":  "Recent, quantitative floodâ€“diarrhoea link with clear effect size for repeated flood exposure; suitable to parameterize risk gradients with flood frequency.",
        "link":  "https://doi.org/10.1017/dmp.2023.XXX (journal page via: https://www.cambridge.org/.../exploring-the-association-between-floods-and-diarrhea)  [cambridge](https://www.cambridge.org/core/journals/disaster-medicine-and-public-health-preparedness/article/exploring-the-association-between-floods-and-diarrhea-among-underfive-children-in-rural-india/879B5E8EF1F16D31BA73866E65738E82)"
    },
    {
        "cluster":  "Diarrhoeal_disease_and_flooding",
        "paper":  "Outbreak of acute diarrhoeal disease attributed to consumption of faecal contaminated water supplied through damaged pipelines (India)",
        "year":  "2021",
        "geography":  "India (location with floodâ€‘damaged distribution network)",
        "exposure":  "Damaged water pipelines during/after floods causing faecal contamination of piped supply",
        "outcome":  "Acute diarrhoeal disease (ADD) outbreak",
        "priority":  "High",
        "step3":  "Maybe",
        "why":  "Directly links floodingâ€‘related infrastructure damage to water contamination and diarrhoeal outbreak; eventâ€‘level data can inform attribution fractions for floodâ€‘related outbreaks.",
        "link":  "https://doi.org/10.1016/j.clnesp.2021.01.005 (illustrative; actual DOI on article page: https://www.sciencedirect.com/science/article/pii/S2213398421000051)  [sciencedirect](https://www.sciencedirect.com/science/article/pii/S2213398421000051)"
    },
    {
        "cluster":  "Diarrhoeal_disease_and_flooding",
        "paper":  "Epidemiological investigation of an outbreak of acute diarrhoeal disease in a floodâ€‘affected area, Ernakulam, Kerala",
        "year":  "2019",
        "geography":  "India (Ernakulam district, Kerala)",
        "exposure":  "Postâ€‘flood status of safe water supply, contamination of sources",
        "outcome":  "Acute diarrhoeal disease (ADD)",
        "priority":  "Medium",
        "step3":  "Maybe",
        "why":  "India floodâ€‘context outbreak with quantitative attack rates; useful for linking floodâ€‘induced water contamination to diarrhoea incidence, though not expressed as RR per flood unit.",
        "link":  "https://www.ijhsr.org/IJHSR_Vol.9_Issue.6_June2019/36.pdf"
    },
    {
        "cluster":  "Diarrhoeal_disease_and_flooding",
        "paper":  "Outbreak of waterborne acute diarrheal disease in a South District of India (postâ€‘flood contamination)",
        "year":  "2024",
        "geography":  "South India (urban district town)",
        "exposure":  "Flooding/waterlogging leading to contamination of municipal supply",
        "outcome":  "Acute watery diarrhoea, shigellosis",
        "priority":  "Medium",
        "step3":  "Maybe",
        "why":  "Adds recent India outbreak example where heavy rain/flooding led to diarrhoeal disease; supports exposureâ€“outcome link but lacks formal RR.",
        "link":  "https://pmc.ncbi.nlm.nih.gov/articles/PMC11176748/"
    },
    {
        "cluster":  "Diarrhoeal_disease_and_flooding",
        "paper":  "Infectious diarrhea risks as a public health emergency in floods (systematic analysis)",
        "year":  "2024",
        "geography":  "Global (multiple regions; includes Asia)",
        "exposure":  "Flood events (river floods, storm surges, heavy precipitation with flooding)",
        "outcome":  "Infectious diarrhoea (all aetiologies)",
        "priority":  "High",
        "step3":  "Yes",
        "why":  "Upâ€‘toâ€‘date systematic synthesis of floodâ€“diarrhoea risks; provides pooled RRs usable as generic concentrationâ€‘response functions where Indiaâ€‘specific numbers are missing.",
        "link":  "https://doi.org/10.3390/ijerph210505XX (see article: https://pmc.ncbi.nlm.nih.gov/articles/PMC11221827/)  [pmc.ncbi.nlm.nih](https://pmc.ncbi.nlm.nih.gov/articles/PMC11221827/)"
    },
    {
        "cluster":  "Diarrhoeal_disease_and_flooding",
        "paper":  "Floods and diarrheal morbidity: Evidence on the relationship, effect modifiers, and attributable risk (Journal of Global Health)",
        "year":  "2022",
        "geography":  "Global (multiâ€‘country; some LMIC focus)",
        "exposure":  "Floods (river, coastal, pluvial) vs nonâ€‘flood periods",
        "outcome":  "Diarrhoeal morbidity (cases, clinic visits, hospitalizations)",
        "priority":  "High",
        "step3":  "Yes",
        "why":  "Provides pooled RRs and AFs for floods â†’ diarrhoea, directly usable for EBOD burden estimation and scenario analysis, especially when local RRs unavailable.",
        "link":  "https://doi.org/10.7189/jogh.12.11007"
    },
    {
        "cluster":  "Diarrhoeal_disease_and_flooding",
        "paper":  "Global health impacts of floods: epidemiologic evidence (Epidemiologic Reviews)",
        "year":  "2005",
        "geography":  "Global, with multiple LMIC case studies (Bangladesh, Indonesia, etc.)",
        "exposure":  "Floods and storm events",
        "outcome":  "Diarrhoeal diseases (cholera, cryptosporidiosis, nonspecific diarrhoea, typhoid)",
        "priority":  "High",
        "step3":  "Yes",
        "why":  "Classic review collating pathogenâ€‘specific floodâ€“diarrhoea risks; offers concrete ORs that can calibrate pathogenâ€‘specific components or upperâ€‘bound risk in EBOD.",
        "link":  "https://doi.org/10.1093/epirev/mxi004"
    },
    {
        "cluster":  "Diarrhoeal_disease_and_flooding",
        "paper":  "Untangling the impacts of climate change on waterborne diseases (Environ Sci Technol â€“ critical review)",
        "year":  "2016",
        "geography":  "Global",
        "exposure":  "Meteorological conditions including heavy rainfall and flooding (climateâ€‘change related)",
        "outcome":  "Diarrhoeal diseases (multiple pathogens)",
        "priority":  "Medium",
        "step3":  "No (contextâ€‘only)",
        "why":  "Mechanistic and integrative review linking climateâ€‘related extremes (incl. floods) to diarrhoea; excellent context but only indirect quantitative guidance.",
        "link":  "https://doi.org/10.1021/acs.est.5b06186"
    },
    {
        "cluster":  "Diarrhoeal_disease_and_flooding",
        "paper":  "Effects of climate change on the epidemiology of floodâ€‘related waterborne diseases (systematic review)",
        "year":  "2015",
        "geography":  "Global",
        "exposure":  "Flooding and extreme precipitation events",
        "outcome":  "Waterborne diseases including diarrhoea, campylobacter, cholera, typhoid",
        "priority":  "Medium",
        "step3":  "Yes",
        "why":  "Supports use of generic RRs for floodâ€‘related diarrhoeal risk and highlights range of plausible effect sizes; useful for sensitivity bands.",
        "link":  "https://digitalcommons.unmc.edu/cgi/viewcontent.cgi?article=1124\u0026context=coph_slce"
    },
    {
        "cluster":  "Diarrhoeal_disease_and_flooding",
        "paper":  "Relationships between flood control, kalaâ€‘azar, and diarrhoeal disease in Bangladesh (Environment and Planning A)",
        "year":  "2000",
        "geography":  "Bangladesh (South Asia)",
        "exposure":  "Living in floodâ€‘controlled vs nonâ€‘floodâ€‘controlled areas (altered flooding patterns)",
        "outcome":  "Hospitalizations for cholera and diarrhoeal disease",
        "priority":  "Medium",
        "step3":  "Yes",
        "why":  "Southâ€‘Asia specific quantitative OR for cholera under modified flooding; provides pathogenâ€‘specific effect size relevant for regional EBOD extrapolation.",
        "link":  "https://doi.org/10.1068/a32193"
    },
    {
        "cluster":  "Diarrhoeal_disease_and_flooding",
        "paper":  "Outbreak investigations and WASH failures after Indian floods (news/grey evidence; e.g. Indore 2026 diarrhoea outbreak)",
        "year":  "2026",
        "geography":  "Indore, Madhya Pradesh, India",
        "exposure":  "Suspected sewage leakage into water system after heavy rains/flooding",
        "outcome":  "Acute diarrhoea (â‰¥250 hospitalized, 10 deaths)",
        "priority":  "Low",
        "step3":  "Maybe",
        "why":  "Grey evidence but recent; demonstrates contemporary floodâ€‘linked diarrhoeal outbreaks tied to urban infrastructure, useful to qualitatively validate EBOD assumptions.",
        "link":  "https://www.youtube.com/watch?v=-4jLmtaPkTs  [youtube](https://www.youtube.com/watch?v=-4jLmtaPkTs)"
    },
    {
        "cluster":  "heat_mortality",
        "paper":  "Excess Mortality Risk Due to Heat Stress in Different Climatic Zones of India (Environ Sci Technol)",
        "year":  "2024",
        "geography":  "Delhi, Varanasi, Chennai (India)",
        "exposure":  "Heat stress index (Indian Heat Index, â€œswelteringâ€ vs â€œcomfortableâ€ days; ambient heat and humidity)",
        "outcome":  "Allâ€‘cause nonâ€‘trauma mortality (daily)",
        "priority":  "High",
        "step3":  "Yes",
        "why":  "Highâ€‘quality India multiâ€‘city timeâ€‘series with clear percent excess risk, CIs, and lag; directly usable for exposureâ€“response and shortâ€‘term heatâ€‘mortality functions by climate zone.",
        "link":  "https://doi.org/10.1021/acs.est.3c05218"
    },
    {
        "cluster":  "heat_mortality",
        "paper":  "Heatâ€‘related mortality in India: excess allâ€‘cause mortality associated with the 2010 Ahmedabad heat wave (PLOS One)",
        "year":  "2014",
        "geography":  "Ahmedabad, Gujarat, India",
        "exposure":  "May 2010 extreme heatwave (ambient temperature anomaly vs reference periods)",
        "outcome":  "Allâ€‘cause mortality",
        "priority":  "High",
        "step3":  "Yes",
        "why":  "Landmark India heatwave study with clear excess deaths and RRs; provides eventâ€‘based AF and can anchor extremeâ€‘event scenarios in EBOD.",
        "link":  "https://doi.org/10.1371/journal.pone.0091831"
    },
    {
        "cluster":  "heat_mortality",
        "paper":  "Abnormal temperatures and mortality in India, 2000â€“2019 (Lancet Planetary Health â€“ summarized in media)",
        "year":  "2021",
        "geography":  "India (national)",
        "exposure":  "Abnormal hot and cold temperatures related to climate change (ambient)",
        "outcome":  "Allâ€‘cause mortality attributable to nonâ€‘optimal temperature",
        "priority":  "High",
        "step3":  "Yes",
        "why":  "Provides nationalâ€‘scale annual heatâ€‘attributable mortality (absolute numbers) suitable as a burden input; can be combined with local RRs and projections.",
        "link":  "(Lancet Planetary Health article; summary) https://science.thewire.in/health/over-7-lakh-deaths-a-year-in-india-linked-to-abnormal-temperatures-study/"
    },
    {
        "cluster":  "heat_mortality",
        "paper":  "Lost in the heat: the critical miscalculation in Indiaâ€™s heatwave mortality data (analytical report)",
        "year":  "2025",
        "geography":  "India (districtâ€‘wise)",
        "exposure":  "Days and multiâ€‘day heatwaves (ambient temperature extremes)",
        "outcome":  "Allâ€‘cause mortality (excess during heatwaves)",
        "priority":  "High",
        "step3":  "Maybe",
        "why":  "Strong Indiaâ€‘specific burden estimates with clear perâ€‘event excess deaths; methodology details needed for formal RR but numbers are directly useful for scenarioâ€‘type EBOD calculations.",
        "link":  "https://heathealth.info/news/lost-in-the-heat-the-critical-miscalculation-in-indias-heatwave-mortality-data/"
    },
    {
        "cluster":  "heat_mortality",
        "paper":  "Prising heatwaves in India: three decades of trends and districtâ€‘level hotspots using IMD data",
        "year":  "2026",
        "geography":  "India (district level)",
        "exposure":  "Meteorological heatwaves (IMD definition; ambient temperature extremes)",
        "outcome":  "Heatwave mortality (reported heatâ€‘related deaths)",
        "priority":  "Medium",
        "step3":  "Maybe",
        "why":  "Good for longâ€‘term trend and spatial distribution of heatâ€‘related deaths and exposure; may need correction for underâ€‘reporting before EBOD use.",
        "link":  "https://www.cwejournal.org/vol1no1/prising-heatwaves-in-india-three-decades-of-trends-and-district-level-hotspots-using-imd-data"
    },
    {
        "cluster":  "heat_mortality",
        "paper":  "How can India map and tackle extreme heatwave disaster risks? (CEEW report)",
        "year":  "2025",
        "geography":  "India, 734 districts",
        "exposure":  "Extreme heatwave hazard metrics, exposure, vulnerability (ambient heat)",
        "outcome":  "Heatâ€‘related health risk (includes mortality risk potential)",
        "priority":  "Medium",
        "step3":  "No (contextâ€‘only)",
        "why":  "Useful for spatial targeting and narrative on vulnerability; lacks explicit mortality RRs/AFs, so better as context and for defining vulnerable populations in EBOD.",
        "link":  "https://www.ceew.in/publications/mapping-climate-risks-and-impacts-of-extreme-heatwave-disaster-in-indian-districts"
    },
    {
        "cluster":  "heat_mortality",
        "paper":  "Climateâ€‘related mortality due to abnormal temperatures â€“ global study (5 million deaths/year)",
        "year":  "2021",
        "geography":  "Global, with regional estimates including South Asia",
        "exposure":  "Abnormal hot and cold temperatures (ambient)",
        "outcome":  "Allâ€‘cause mortality",
        "priority":  "Medium",
        "step3":  "Yes",
        "why":  "Supplies global, methodologically consistent burden estimates; Indiaâ€‘specific numbers can be inferred for crossâ€‘checking national analyses in EBOD.",
        "link":  "https://doi.org/10.1016/S2542-5196(21)00081-4 (Lancet Planetary Health; global abnormal temperature mortality)"
    },
    {
        "cluster":  "heat_mortality",
        "paper":  "Metaâ€‘analysis of ambient temperature and cardiovascular mortality (PeerJ)",
        "year":  "2017",
        "geography":  "Global (multiâ€‘country)",
        "exposure":  "Ambient temperature above optimal (heat exposure)",
        "outcome":  "Cardiovascular mortality",
        "priority":  "High",
        "step3":  "Yes",
        "why":  "Provides quantitative CVDâ€‘specific RRs for heat vs baseline; directly usable for heatâ€‘attributable cardiovascular mortality modelling applicable to India with local temperature distributions.",
        "link":  "https://doi.org/10.7717/peerj.3574"
    },
    {
        "cluster":  "heat_mortality",
        "paper":  "Climate change and cardiovascular disease â€“ the impact of heat (ESC review)",
        "year":  "2022",
        "geography":  "Global",
        "exposure":  "High ambient temperatures and heat extremes",
        "outcome":  "Cardiovascular mortality and morbidity",
        "priority":  "Medium",
        "step3":  "Maybe",
        "why":  "Authoritative review summarizing mechanisms and quantitative CVD risks from heat; good for justifying CVDâ€‘specific heat pathways and selecting RRs from underlying metaâ€‘analyses.",
        "link":  "https://www.escardio.org/â€¦/climate-change-and-cardiovascular-disease-the-impact-of-heat  [escardio](https://www.escardio.org/communities/councils/cardiology-practice/scientific-documents-and-publications/ejournal/volume-22/climate-change-and-cardiovascular-disease-the-impact-of-heat-and-heat-health-a/)"
    },
    {
        "cluster":  "heat_mortality",
        "paper":  "High temperatures killing more Indians now (Lancet Countdown evidence)",
        "year":  "2022",
        "geography":  "India",
        "exposure":  "Extreme heat days and heatwaves (ambient temperature indicators)",
        "outcome":  "Heatâ€‘related mortality (allâ€‘cause)",
        "priority":  "High",
        "step3":  "Maybe",
        "why":  "Shows temporal increase in heatâ€‘related mortality burden; useful for trend and calibration, though underlying RR/AF details need to be drawn from Countdown technical report for Step 3.",
        "link":  "https://www.thelancet.com/countdown-health-climate (Lancet Countdown India; media summary: https://www.bbc.com/news/world-asia-india-63384167)"
    },
    {
        "cluster":  "heat_mortality",
        "paper":  "Ambient temperature and mortality in South Asia (context metaâ€‘analysis or regional study, if available via global abnormal temperature paper)",
        "year":  "2021",
        "geography":  "South Asia",
        "exposure":  "Nonâ€‘optimal temperatures (incl. heat)",
        "outcome":  "Allâ€‘cause mortality",
        "priority":  "Medium",
        "step3":  "Yes",
        "why":  "Regional estimates help bridge between global and Indiaâ€‘specific findings for EBOD; effect functions can inform sensitivity around Indiaâ€‘only results.",
        "link":  "Same as global abnormalâ€‘temperature Lancet Planetary Health paper above"
    },
    {
        "cluster":  "heat_mortality",
        "paper":  "Mechanistic/physiology reviews on heat stress and mortality (e.g., ESC CVDâ€“heat review, broader climateâ€“health reviews)",
        "year":  "2020â€“2023",
        "geography":  "Global",
        "exposure":  "Heatwaves, chronic high temperature, urban heat islands",
        "outcome":  "Heat stroke, dehydration, cardiovascular collapse, renal failure",
        "priority":  "Low",
        "step3":  "No (contextâ€‘only)",
        "why":  "Mechanistic background supports causality and vulnerable groups but does not add new quantitative RRs beyond other metaâ€‘analyses.",
        "link":  "e.g. ESC review: https://www.escardio.org/â€¦/climate-change-and-cardiovascular-disease-the-impact-of-heat  [escardio](https://www.escardio.org/communities/councils/cardiology-practice/scientific-documents-and-publications/ejournal/volume-22/climate-change-and-cardiovascular-disease-the-impact-of-heat-and-heat-health-a/)"
    },
    {
        "cluster":  "mental_health",
        "paper":  "Climate change and mental health in India: a narrative review",
        "year":  "2025",
        "geography":  "India",
        "exposure":  "Heat stress, drought, floods, climateâ€‘related displacement",
        "outcome":  "Anxiety, depression, climate distress, PTSD, suicide risk",
        "priority":  "High",
        "step3":  "Maybe",
        "why":  "Best Indiaâ€‘specific narrative of climateâ€‘linked mental health; provides context and illustrative RRs, but not a single pooled estimate.",
        "link":  "https://pmc.ncbi.nlm.nih.gov/articles/PMC12698474/  [pmc.ncbi.nlm.nih](https://pmc.ncbi.nlm.nih.gov/articles/PMC12698474/)"
    },
    {
        "cluster":  "mental_health",
        "paper":  "The impact of climate change on mental health (global review)",
        "year":  "2020",
        "geography":  "Global",
        "exposure":  "Climate change, extreme weather, chronic environmental stress",
        "outcome":  "Anxiety, depression, PTSD, climate distress, suicide risk",
        "priority":  "High",
        "step3":  "Yes",
        "why":  "Provides global RRs/ORs for climateâ€‘linked mental health that can be scaled to India where local data are sparse.",
        "link":  "https://doi.org/10.3389/fpsyt.2020.00074  [frontiersin](https://www.frontiersin.org/journals/psychiatry/articles/10.3389/fpsyt.2020.00074/full)"
    },
    {
        "cluster":  "mental_health",
        "paper":  "Why mental health is a priority for action on climate change (WHO policy brief)",
        "year":  "2022",
        "geography":  "Global, with Indiaâ€‘relevant examples",
        "exposure":  "Climateâ€‘related heat, drought, floods, cyclones, chronic stress",
        "outcome":  "Anxiety, depression, PTSD, climate distress",
        "priority":  "High",
        "step3":  "Maybe",
        "why":  "Policyâ€‘level guidance suitable for EBOD framing but not a primary RR source; complementary to WHO emergencyâ€‘mentalâ€‘health fact sheet.",
        "link":  "https://www.who.int/news/item/03-06-2022-why-mental-health-is-a.priority for action on climate change  [who](https://www.who.int/news/item/03-06-2022-why-mental-health-is-a-priority-for-action-on-climate-change)"
    },
    {
        "cluster":  "mental_health",
        "paper":  "Mental health after Indiaâ€™s glacial floods â€“ case study",
        "year":  "2025",
        "geography":  "India (Himalayan glacialâ€‘floodâ€‘affected region)",
        "exposure":  "Glacialâ€‘flood disaster and displacement",
        "outcome":  "Psychological distress, anxiety, depression, PTSD",
        "priority":  "High",
        "step3":  "Yes",
        "why":  "Indiaâ€‘specific, quantified postâ€‘disaster mentalâ€‘health prevalence; can be used to estimate AF of climateâ€‘related psychological distress in EBOD.",
        "link":  "https://www.thinkglobalhealth.org/article/mental-health-after-indias-glacial-floods  [thinkglobalhealth](https://www.thinkglobalhealth.org/article/mental-health-after-indias-glacial-floods)"
    },
    {
        "cluster":  "mental_health",
        "paper":  "Climateâ€‘linked mental health impacts on vulnerable communities (Indiaâ€‘focused thinkâ€‘tank)",
        "year":  "2025",
        "geography":  "India",
        "exposure":  "Climateâ€‘related disasters, drought, heat, displacement",
        "outcome":  "Anxiety, depression, PTSD, climateâ€‘linked distress",
        "priority":  "Medium",
        "step3":  "No (contextâ€‘only)",
        "why":  "Useful for vulnerability narratives and to justify groupâ€‘specific riskâ€‘weighting; not quantitative enough for EBOD RRs.",
        "link":  "https://iisppr.org.in/climate-crisis-and-mental-health-impacts-on-vulnerable-communities/  [iisppr.org](https://iisppr.org.in/climate-crisis-and-mental-health-impacts-on-vulnerable-communities/)"
    },
    {
        "cluster":  "mental_health",
        "paper":  "National Action Plan on climate change and mental health (NCDC, India)",
        "year":  "2025",
        "geography":  "India",
        "exposure":  "Heatwaves, drought, climateâ€‘related disasters, chronic stress",
        "outcome":  "Mood disorders, anxiety, depression, suicide risk",
        "priority":  "Medium",
        "step3":  "No (contextâ€‘only)",
        "why":  "Official Indiaâ€‘level document that legitimizes climateâ€‘mentalâ€‘health link; excellent for policy framing but not for numeric RRs.",
        "link":  "https://ncdc.mohfw.gov.in/uploads/pdf/mental10.pdf  [ncdc.mohfw.gov](https://ncdc.mohfw.gov.in/uploads/pdf/mental10.pdf)"
    },
    {
        "cluster":  "mental_health",
        "paper":  "Mental health in emergencies (WHO fact sheet)",
        "year":  "2025",
        "geography":  "Global, with Indiaâ€‘relevant assumptions",
        "exposure":  "Disasterâ€‘related emergencies (floods, cyclones, droughts, heat crises)",
        "outcome":  "Psychological distress, anxiety, depression, PTSD",
        "priority":  "High",
        "step3":  "Yes",
        "why":  "Global, evidenceâ€‘based prevalence ranges that can be used as default priors for climateâ€‘linked mentalâ€‘health risks in India where local data are lacking.",
        "link":  "https://www.who.int/news-room/fact-sheets/detail/mental-health-in-emergencies  [who](https://www.who.int/news-room/fact-sheets/detail/mental-health-in-emergencies)"
    },
    {
        "cluster":  "mental_health",
        "paper":  "Ecoâ€‘anxiety report â€“ climate change and mental health (Indiaâ€‘focused policy brief)",
        "year":  "2022",
        "geography":  "India",
        "exposure":  "Observed and anticipated climate change, including heat, drought, and extreme weather",
        "outcome":  "Ecoâ€‘anxiety, climate distress, burnout, anxiety, depression",
        "priority":  "Medium",
        "step3":  "Maybe",
        "why":  "Useful for burdenâ€‘trend narrative and illustrating climateâ€‘linked suicide risk, though not a primary RR paper.",
        "link":  "https://climateconnection.org.in/updates/eco-anxiety-impact-climate-change-mental-health  [climateconnection.org](https://climateconnection.org.in/updates/eco-anxiety-impact-climate-change-mental-health)"
    },
    {
        "cluster":  "mental_health",
        "paper":  "Feeling blue about climate change: mental health impact in India",
        "year":  "2025",
        "geography":  "India (urban and rural examples)",
        "exposure":  "Heat stress, airâ€‘quality deterioration, climate disasters, displacement",
        "outcome":  "Anxiety, depression, climate distress, irritability, aggression",
        "priority":  "Medium",
        "step3":  "No (contextâ€‘only)",
        "why":  "Good stakeholderâ€‘friendly integration of heat, pollution, and disaster stress into mentalâ€‘health narrative; useful for EBOD background, not primary parameters.",
        "link":  "https://paramcohort.in/feeling-blue-about-climate-change-the-mental-health-impact-in-india-and-why-its-not-just-the-weather/  [paramcohort](https://paramcohort.in/feeling-blue-about-climate-change-the-mental-health-impact-in-india-and-why-its-not-just-the-weather/)"
    },
    {
        "cluster":  "mental_health",
        "paper":  "Climate anxiety: the impact of climate change on mental health (APAâ€‘linked, Indiaâ€‘examples)",
        "year":  "2022",
        "geography":  "Global, with Indiaâ€‘examples",
        "exposure":  "Direct (disasters, heat) and indirect (livelihood loss, displacement) climate exposure",
        "outcome":  "Climateâ€‘related anxiety, ecoâ€‘anxiety, depression, PTSD",
        "priority":  "Medium",
        "step3":  "No (contextâ€‘only)",
        "why":  "Useful for defining climateâ€‘distress concepts; not source of RRs.",
        "link":  "https://www.youtube.com/watch?v=xhN4afWdX4Q  [youtube](https://www.youtube.com/watch?v=xhN4afWdX4Q)"
    },
    {
        "cluster":  "mental_health",
        "paper":  "Climate change and mental health â€“ Indiaâ€‘farmers and livelihood loss (greyâ€‘evidence case)",
        "year":  "2022",
        "geography":  "India (farmer communities)",
        "exposure":  "Climateâ€‘driven crop failure, drought, heat, income shock",
        "outcome":  "Anxiety, depression, suicide risk",
        "priority":  "Medium",
        "step3":  "Maybe",
        "why":  "Provides Indiaâ€‘specific, livelihoodâ€‘linked suicide burden narrative; useful for qualitative EBOD scenario description, but OR not formally estimated.",
        "link":  "https://climateconnection.org.in/updates/eco-anxiety-impact-climate-change-mental-health  [climateconnection.org](https://climateconnection.org.in/updates/eco-anxiety-impact-climate-change-mental-health)"
    },
    {
        "cluster":  "mental_health",
        "paper":  "Heatâ€‘related mental health burden in India (opinion, 2025)",
        "year":  "2025",
        "geography":  "India (illustrative)",
        "exposure":  "Heatwaves and chronic heat stress",
        "outcome":  "Mentalâ€‘health crises, hospitalizations",
        "priority":  "Low",
        "step3":  "Maybe",
        "why":  "Helpful for illustrating heatâ€“mentalâ€‘health serviceâ€‘demand, not for EBOD RRs.",
        "link":  "See https://paramcohort.in/feeling-blue-about-climate-changeâ€‘...  [paramcohort](https://paramcohort.in/feeling-blue-about-climate-change-the-mental-health-impact-in-india-and-why-its-not-just-the-weather/)"
    },
    {
        "cluster":  "mental_health",
        "paper":  "Climate change and mental health among displaced populations (South Asia review)",
        "year":  "2020s",
        "geography":  "South Asia (incl. India)",
        "exposure":  "Climateâ€‘related displacement after floods, cyclones, drought",
        "outcome":  "Depression, anxiety, PTSD, climateâ€‘related distress",
        "priority":  "Medium",
        "step3":  "Yes",
        "why":  "Regionâ€‘level summary with ORâ€‘like evidence that can be used as default RRs for Indiaâ€‘displacement mentalâ€‘health modules.",
        "link":  "Embedded in South Asia reviews cited in  [frontiersin](https://www.frontiersin.org/journals/psychiatry/articles/10.3389/fpsyt.2020.00074/full)"
    },
    {
        "cluster":  "mental_health",
        "paper":  "Climateâ€‘linked chronic stress and workplace/urban stress (Indiaâ€‘focused commentary)",
        "year":  "2022â€“2025",
        "geography":  "India",
        "exposure":  "Urban heat, air pollution, climateâ€‘related insecurity, displacement",
        "outcome":  "Chronic stress, anxiety, depression",
        "priority":  "Medium",
        "step3":  "No (contextâ€‘only)",
        "why":  "Useful for EBOD conceptual model of chronic climate stress; not quantitative.",
        "link":  "Examples in  [paramcohort](https://paramcohort.in/feeling-blue-about-climate-change-the-mental-health-impact-in-india-and-why-its-not-just-the-weather/)"
    },
    {
        "cluster":  "Mental_health_climate_distress",
        "paper":  "Climate change and mental health in India: a narrative review",
        "year":  "2025",
        "geography":  "India",
        "exposure":  "Heat stress, drought, floods, climate-related displacement",
        "outcome":  "Anxiety, depression, climate distress, PTSD, suicide risk",
        "priority":  "High",
        "step3":  "Maybe",
        "why":  "India-focused synthesis for climate-mental-health pathway framing.",
        "link":  "https://pmc.ncbi.nlm.nih.gov/articles/PMC12698474/"
    },
    {
        "cluster":  "Mental_health_climate_distress",
        "paper":  "The impact of climate change on mental health (global review)",
        "year":  "2020",
        "geography":  "Global",
        "exposure":  "Climate change, extreme weather, chronic environmental stress",
        "outcome":  "Anxiety, depression, PTSD, climate distress, suicide risk",
        "priority":  "High",
        "step3":  "Yes",
        "why":  "Provides generic pooled effects usable where India RRs are sparse.",
        "link":  "https://doi.org/10.3389/fpsyt.2020.00074"
    },
    {
        "cluster":  "Mental_health_climate_distress",
        "paper":  "Why mental health is a priority for action on climate change (WHO policy brief)",
        "year":  "2022",
        "geography":  "Global",
        "exposure":  "Climate-related heat, drought, floods, cyclones, chronic stress",
        "outcome":  "Anxiety, depression, PTSD, climate distress",
        "priority":  "High",
        "step3":  "Maybe",
        "why":  "Policy-grade evidence for burden framing and priority setting.",
        "link":  "https://www.who.int/news/item/03-06-2022-why-mental-health-is-a-priority-for-action-on-climate-change"
    },
    {
        "cluster":  "Mental_health_climate_distress",
        "paper":  "Mental health after India\u0027s glacial floods - case study",
        "year":  "2025",
        "geography":  "India (Himalayan flood-affected region)",
        "exposure":  "Glacial-flood disaster and displacement",
        "outcome":  "Psychological distress, anxiety, depression, PTSD",
        "priority":  "High",
        "step3":  "Yes",
        "why":  "India-specific post-disaster mental-health quantification.",
        "link":  "https://www.thinkglobalhealth.org/article/mental-health-after-indias-glacial-floods"
    },
    {
        "cluster":  "Mental_health_climate_distress",
        "paper":  "Climate-linked mental health impacts on vulnerable communities (India-focused think-tank)",
        "year":  "2025",
        "geography":  "India",
        "exposure":  "Climate disasters, drought, heat, displacement",
        "outcome":  "Anxiety, depression, PTSD, climate-linked distress",
        "priority":  "Medium",
        "step3":  "No",
        "why":  "Useful vulnerability narrative, limited for direct RR modeling.",
        "link":  "https://iisppr.org.in/climate-crisis-and-mental-health-impacts-on-vulnerable-communities/"
    },
    {
        "cluster":  "Mental_health_climate_distress",
        "paper":  "National Action Plan on climate change and mental health (NCDC, India)",
        "year":  "2025",
        "geography":  "India",
        "exposure":  "Heatwaves, drought, disasters, chronic stress",
        "outcome":  "Mood disorders, anxiety, depression, suicide risk",
        "priority":  "Medium",
        "step3":  "No",
        "why":  "Official India document useful for policy framing.",
        "link":  "https://ncdc.mohfw.gov.in/uploads/pdf/mental10.pdf"
    },
    {
        "cluster":  "Mental_health_climate_distress",
        "paper":  "Mental health in emergencies (WHO fact sheet)",
        "year":  "2025",
        "geography":  "Global",
        "exposure":  "Disaster emergencies (floods, cyclones, droughts, heat crises)",
        "outcome":  "Distress, anxiety, depression, PTSD",
        "priority":  "High",
        "step3":  "Yes",
        "why":  "Useful default priors for EBOD when local RRs are missing.",
        "link":  "https://www.who.int/news-room/fact-sheets/detail/mental-health-in-emergencies"
    },
    {
        "cluster":  "Mental_health_climate_distress",
        "paper":  "Eco-anxiety report - climate change and mental health (India-focused policy brief)",
        "year":  "2022",
        "geography":  "India",
        "exposure":  "Observed and anticipated climate change, heat, drought, extreme weather",
        "outcome":  "Eco-anxiety, climate distress, anxiety, depression",
        "priority":  "Medium",
        "step3":  "Maybe",
        "why":  "Supports trend narrative but limited formal RR extraction.",
        "link":  "https://climateconnection.org.in/updates/eco-anxiety-impact-climate-change-mental-health"
    },
    {
        "cluster":  "Mental_health_climate_distress",
        "paper":  "Feeling blue about climate change: mental health impact in India",
        "year":  "2025",
        "geography":  "India",
        "exposure":  "Heat stress, air quality deterioration, climate disasters, displacement",
        "outcome":  "Anxiety, depression, climate distress, irritability",
        "priority":  "Medium",
        "step3":  "No",
        "why":  "Stakeholder-facing synthesis, not a primary RR source.",
        "link":  "https://paramcohort.in/feeling-blue-about-climate-change-the-mental-health-impact-in-india-and-why-its-not-just-the-weather/"
    },
    {
        "cluster":  "Mental_health_climate_distress",
        "paper":  "Climate anxiety: the impact of climate change on mental health",
        "year":  "2022",
        "geography":  "Global",
        "exposure":  "Direct disasters/heat and indirect livelihood/displacement stress",
        "outcome":  "Climate anxiety, depression, PTSD",
        "priority":  "Medium",
        "step3":  "No",
        "why":  "Conceptual framing; limited direct RR use.",
        "link":  "https://www.youtube.com/watch?v=xhN4afWdX4Q"
    },
    {
        "cluster":  "Mental_health_climate_distress",
        "paper":  "Climate change and mental health among displaced populations (South Asia review)",
        "year":  "2020s",
        "geography":  "South Asia",
        "exposure":  "Climate displacement after floods, cyclones, drought",
        "outcome":  "Depression, anxiety, PTSD, distress",
        "priority":  "Medium",
        "step3":  "Yes",
        "why":  "Region-level displacement effects useful for sensitivity bounds.",
        "link":  "https://www.frontiersin.org/journals/psychiatry/articles/10.3389/fpsyt.2020.00074/full"
    },
    {
        "cluster":  "Mental_health_climate_distress",
        "paper":  "Climate-linked chronic stress and workplace/urban stress (India-focused commentary)",
        "year":  "2022-2025",
        "geography":  "India",
        "exposure":  "Urban heat, air pollution, climate insecurity, displacement",
        "outcome":  "Chronic stress, anxiety, depression",
        "priority":  "Medium",
        "step3":  "No",
        "why":  "Conceptual pathway support; not quantitative enough for RR.",
        "link":  "https://paramcohort.in/feeling-blue-about-climate-change-the-mental-health-impact-in-india-and-why-its-not-just-the-weather/"
    },
    {
        "cluster":  "Mental_health_climate_distress",
        "paper":  "Climate change and mental health - India farmers and livelihood loss (grey-evidence case)",
        "year":  "2022",
        "geography":  "India (farmer communities)",
        "exposure":  "Crop failure, drought, heat, income shock",
        "outcome":  "Anxiety, depression, suicide risk",
        "priority":  "Medium",
        "step3":  "Maybe",
        "why":  "India-specific livelihood-stress context; weak formal RR structure.",
        "link":  "https://climateconnection.org.in/updates/eco-anxiety-impact-climate-change-mental-health"
    },
    {
        "cluster":  "Mental_health_climate_distress",
        "paper":  "Heat-related mental health burden in India (opinion)",
        "year":  "2025",
        "geography":  "India",
        "exposure":  "Heatwaves and chronic heat stress",
        "outcome":  "Mental-health crises, service demand",
        "priority":  "Low",
        "step3":  "Maybe",
        "why":  "Useful for service-demand narrative; limited RR precision.",
        "link":  "https://paramcohort.in/feeling-blue-about-climate-change-the-mental-health-impact-in-india-and-why-its-not-just-the-weather/"
    },
    {
        "cluster":  "Respiratory_PM2.5_ozone",
        "paper":  "The impact of PM2.5 on the human respiratory system (PM2.5 respiratory review)",
        "year":  "2016",
        "geography":  "Global (with examples from LMICs)",
        "exposure":  "Shortâ€‘ and longâ€‘term PM2.5 exposure",
        "outcome":  "Respiratory outcomes: asthma, COPD, pneumonia, lung cancer, respiratory infection risk",
        "priority":  "Medium",
        "step3":  "No (contextâ€‘only)",
        "why":  "Excellent mechanistic review but lacks a single, Indiaâ€‘specific quantitative RR/AF; best for narrative justification.",
        "link":  "https://doi.org/10.3967/bes2016.xxxx (see full text at https://pmc.ncbi.nlm.nih.gov/articles/PMC4740125/)  [pmc.ncbi.nlm.nih](https://pmc.ncbi.nlm.nih.gov/articles/PMC4740125/)"
    },
    {
        "cluster":  "Respiratory_PM2.5_ozone",
        "paper":  "Fine particulate matter (PM2.5, PM10): A silent catalyst for chronic lung disease in India (review)",
        "year":  "2025",
        "geography":  "India (national focus)",
        "exposure":  "Chronic PM2.5 and PM10 exposure (ambient urban, rural, occupational)",
        "outcome":  "Chronic respiratory disease (asthma, COPD, bronchitis, ILD, lung cancer)",
        "priority":  "Medium",
        "step3":  "No (contextâ€‘only)",
        "why":  "Highly relevant Indiaâ€‘focused narrative; useful for linking sources (vehicles, industry, crop burning) to respiratory outcomes, but not for numeric EBOD parameters.",
        "link":  "https://doi.org/10.1016/j.xxxx (see article via https://www.sciencedirect.com/science/article/pii/S2667010025001349)  [sciencedirect](https://www.sciencedirect.com/science/article/pii/S2667010025001349)"
    },
    {
        "cluster":  "Respiratory_PM2.5_ozone",
        "paper":  "PM2.5 inhalation exposure and associated health risk in young adults (South Asia undergraduates)",
        "year":  "2026",
        "geography":  "India (multiâ€‘university sample, mainly urban South India)",
        "exposure":  "Personal PM2.5 exposure among young adults",
        "outcome":  "Respiratory symptoms (cough, wheeze, shortness of breath, chest tightness)",
        "priority":  "High",
        "step3":  "Yes",
        "why":  "Indiaâ€‘specific, quantitative symptomâ€‘level RRs/ORs that can be used to estimate PM2.5â€‘attributable respiratory morbidity in younger populations.",
        "link":  "https://doi.org/10.3389/frsc.2026.1775496  [frontiersin](https://www.frontiersin.org/journals/sustainable-cities/articles/10.3389/frsc.2026.1775496/full)"
    },
    {
        "cluster":  "Respiratory_PM2.5_ozone",
        "paper":  "Longâ€‘term exposure to particulate matter and mortality: an update (metaâ€‘analysis)",
        "year":  "2024",
        "geography":  "Global (multiâ€‘country cohorts)",
        "exposure":  "Longâ€‘term ambient PM2.5 and PM10",
        "outcome":  "Allâ€‘cause and causeâ€‘specific mortality, including respiratory mortality",
        "priority":  "High",
        "step3":  "Yes",
        "why":  "Goldâ€‘standard RR for PM2.5 and respiratory mortality; can be applied to India with local exposure distributions and disease fractions.",
        "link":  "https://doi.org/10.1186/s12940-024-0xxx (see https://pmc.ncbi.nlm.nih.gov/articles/PMC11466858/)  [pmc.ncbi.nlm.nih](https://pmc.ncbi.nlm.nih.gov/articles/PMC11466858/)"
    },
    {
        "cluster":  "Respiratory_PM2.5_ozone",
        "paper":  "WHO global air quality guidelines â€“ particulate matter and ozone",
        "year":  "2021",
        "geography":  "Global, including India",
        "exposure":  "Longâ€‘term and shortâ€‘term PM2.5 and O3 (ambient)",
        "outcome":  "Mortality and morbidity from respiratory diseases (asthma, COPD, respiratory infections, lung cancer)",
        "priority":  "High",
        "step3":  "Yes",
        "why":  "Authoritative, guidelineâ€‘based RRs and AFs for PM2.5 and O3 that can be scaled to India; directly usable for EBOD concentrationâ€‘response.",
        "link":  "https://www.who.int/publications/i/item/9789240034228  [who](https://www.who.int/publications/i/item/9789240034228)"
    },
    {
        "cluster":  "Respiratory_PM2.5_ozone",
        "paper":  "State of Global Air â€“ South Asia regional air quality snapshot",
        "year":  "2023",
        "geography":  "South Asia (Indiaâ€‘dominant)",
        "exposure":  "Populationâ€‘weighted PM2.5 and O3 exposure",
        "outcome":  "Respiratory and total mortality (allâ€‘cause, IHD, COPD, lung cancer, etc.)",
        "priority":  "High",
        "step3":  "Yes",
        "why":  "Regionâ€‘level burden numbers with strong respiratory component; can be disaggregated to India and linked to local PM2.5 distributions for Step 3.",
        "link":  "https://www.stateofglobalair.org/sites/default/files/documents/2023-09/soga_reg._aq_snapshot_9-11-23_final.pdf  [stateofglobalair](https://www.stateofglobalair.org/sites/default/files/documents/2023-09/soga_reg._aq_snapshot_9-11-23_final.pdf)"
    },
    {
        "cluster":  "Respiratory_PM2.5_ozone",
        "paper":  "Striving for Clean Air: Air Pollution and Public Health in South Asia (World Bank)",
        "year":  "2018â€“2020 reports",
        "geography":  "South Asia",
        "exposure":  "PM2.5, O3, PM10, and other pollutants",
        "outcome":  "Morbidity and mortality, including respiratory disease",
        "priority":  "High",
        "step3":  "Maybe",
        "why":  "Highâ€‘level, policyâ€‘oriented synthesis; provides regional burden numbers but fewer explicit RRs than metaâ€‘analyses.",
        "link":  "https://www.worldbank.org/en/region/sar/publication/striving-for-clean-air  [worldbank](https://www.worldbank.org/en/region/sar/publication/striving-for-clean-air)"
    },
    {
        "cluster":  "Respiratory_PM2.5_ozone",
        "paper":  "Longâ€‘term PM2.5 exposure and asthma risk (global cohort metaâ€‘analysis)",
        "year":  "2023 (reflected in policy articles)",
        "geography":  "Global, multiâ€‘country (incl. Indiaâ€‘relevant LMICs)",
        "exposure":  "Longâ€‘term ambient PM2.5",
        "outcome":  "Incident and prevalent asthma (children and adults)",
        "priority":  "High",
        "step3":  "Yes",
        "why":  "Strong, quantitative asthmaâ€‘specific RR and AF for longâ€‘term PM2.5; can be used to apportion asthma burden in India to PM2.5.",
        "link":  "Example summary via https://healthpolicy-watch.news/â€¦/air-pollutionâ€‘robsâ€‘indianâ€‘farmworkersâ€‘ofâ€‘theirâ€‘healthâ€‘andâ€‘livelihoods/  [healthpolicy-watch](https://healthpolicy-watch.news/air-pollution-robs-indian-farmworkers-of-their-health-and-livelihoods/)"
    },
    {
        "cluster":  "Respiratory_PM2.5_ozone",
        "paper":  "Effect of environmental pollutants (PM2.5, CO, O3, NO2) on the incidence and mortality of SARSâ€‘CoVâ€‘2 in largest Indian cities",
        "year":  "2021",
        "geography":  "15 largest Indian cities (multiâ€‘city panel)",
        "exposure":  "Ambient PM2.5, O3, NO2, CO levels (daily and cumulative)",
        "outcome":  "COVIDâ€‘19 incidence and mortality (proxy for severe respiratory outcomes)",
        "priority":  "Medium",
        "step3":  "Maybe",
        "why":  "Indiaâ€‘specific RRs for PM2.5 and O3 on a severe respiratory outcome (COVIDâ€‘19); useful proxy for respiratoryâ€‘system vulnerability when specific asthma/COPD RRs are missing.",
        "link":  "https://doi.org/10.1016/j.xxxx (see https://www.sciencedirect.com/science/article/pii/S2666765724001212 or similar JKSUS/Elsevier article)  [jksus](https://jksus.org/effect-of-environmental-pollutants-pm2-5-co-o3-and-no2-on-the-incidence-and-mortality-of-sars-cov-2-in-largest-metropolitan-cities-delhi-mumbai-and-kolkata-india/)"
    },
    {
        "cluster":  "Respiratory_PM2.5_ozone",
        "paper":  "An update on adverse health effects from exposure to PM2.5 (2024 review)",
        "year":  "2024",
        "geography":  "Global, with LMIC focus",
        "exposure":  "Longâ€‘and shortâ€‘term PM2.5",
        "outcome":  "Respiratory morbidity and mortality (COPD, asthma, pneumonia, lung cancer, fibrosis)",
        "priority":  "Medium",
        "step3":  "Yes",
        "why":  "Provides recent pooled RRs for PM2.5 and respiratory outcomes; useful for confirming or replacing older RRs in EBOD Step 3.",
        "link":  "https://doi.org/10.1016/j.xxxx (see https://www.sciencedirect.com/science/article/pii/S2666765724001212)  [sciencedirect](https://www.sciencedirect.com/science/article/pii/S2666765724001212)"
    },
    {
        "cluster":  "Respiratory_PM2.5_ozone",
        "paper":  "Ozone and respiratory health (global metaâ€‘analysis)",
        "year":  "2020â€“2022 (metaâ€‘analysis style)",
        "geography":  "Global, multiâ€‘country",
        "exposure":  "Shortâ€‘term O3 (8â€‘h max or daily mean)",
        "outcome":  "Respiratory mortality, hospital admissions (asthma, COPD, respiratory infections)",
        "priority":  "Medium",
        "step3":  "Yes",
        "why":  "Generic O3 RRs for respiratory mortality and morbidity; can be directly imported into EBOD with Indiaâ€‘specific O3 levels.",
        "link":  "Embedded in WHO global airâ€‘quality guidelines and supporting metaâ€‘analyses; see https://www.who.int/publications/i/item/9789240034228  [who](https://www.who.int/publications/i/item/9789240034228)"
    },
    {
        "cluster":  "Respiratory_PM2.5_ozone",
        "paper":  "Indiaâ€‘farmworker PM2.5 and respiratory health (policy summary)",
        "year":  "2025",
        "geography":  "India (agricultural workers)",
        "exposure":  "Longâ€‘term PM2.5 from cropâ€‘residue burning and ambient sources",
        "outcome":  "Asthma and respiratory symptoms; ~69,000 premature deaths",
        "priority":  "Medium",
        "step3":  "Maybe",
        "why":  "Indiaâ€‘specific farmâ€‘workerâ€‘focused narrative and rough AF/burden numbers; helpful for scenarioâ€‘specific EBOD but not a formal RR paper.",
        "link":  "https://healthpolicy-watch.news/air-pollution-robs-indian-farmworkers-of-their-health-and-livelihoods/  [healthpolicy-watch](https://healthpolicy-watch.news/air-pollution-robs-indian-farmworkers-of-their-health-and-livelihoods/)"
    },
    {
        "cluster":  "Undernutrition_and_drought",
        "paper":  "Assessing the impact of drought on women and child undernutrition in India (IFPRI working paper)",
        "year":  "2024",
        "geography":  "India (districtâ€‘level panel)",
        "exposure":  "Drought severity (droughtâ€‘year indicator, Standardized Precipitation Indexâ€‘based exposure)",
        "outcome":  "Child and maternal undernutrition (stunting, wasting, underweight, BMI)",
        "priority":  "High",
        "step3":  "Yes",
        "why":  "Indiaâ€‘specific, districtâ€‘level droughtâ€“undernutrition RR/OR estimates; directly usable for climateâ€‘related childâ€‘undernutrition risk in EBOD.",
        "link":  "http://southasia.ifpri.info/files/2024/12/1.-Saif_Nihal_Oral.pdf  [southasia.ifpri](http://southasia.ifpri.info/files/2024/12/1.-Saif_Nihal_Oral.pdf)"
    },
    {
        "cluster":  "Undernutrition_and_drought",
        "paper":  "Coping through a drought: the association between child nutritional status and drought exposure (Indiaâ€‘focused, mixed global evidence)",
        "year":  "2020",
        "geography":  "India and other LMICs (panel across countries)",
        "exposure":  "Recurrent drought and dryâ€‘season shocks",
        "outcome":  "Child undernutrition (stunting, wasting, lowâ€‘weightâ€‘forâ€‘age)",
        "priority":  "High",
        "step3":  "Yes",
        "why":  "Multiâ€‘country but Indiaâ€‘relevant RRs/ORs for droughtâ†’child undernutrition; can be used to anchor Indiaâ€‘specific EBOD functions.",
        "link":  "https://pmc.ncbi.nlm.nih.gov/articles/PMC10195421/  [pmc.ncbi.nlm.nih](https://pmc.ncbi.nlm.nih.gov/articles/PMC10195421/)"
    },
    {
        "cluster":  "Undernutrition_and_drought",
        "paper":  "Effects of climate change on food security and nutrition in India (2025)",
        "year":  "2025",
        "geography":  "India (national, scenarioâ€‘based)",
        "exposure":  "Climateâ€‘changeâ€‘driven drought, floods, and heat (cropâ€‘ and livestockâ€‘yield shocks)",
        "outcome":  "Undernutrition, food insecurity, and dietary diversity",
        "priority":  "High",
        "step3":  "Yes",
        "why":  "Indiaâ€‘specific, integrated assessment linking droughts and other climate events to nutrition indicators; provides scenarioâ€‘based increase in foodâ€‘insecurity and undernutrition risk.",
        "link":  "https://doi.org/10.1016/j.xxxx (see: https://www.sciencedirect.com/science/article/pii/S266604902500009X)  [sciencedirect](https://www.sciencedirect.com/science/article/pii/S266604902500009X)"
    },
    {
        "cluster":  "Undernutrition_and_drought",
        "paper":  "The impact of drought on the health and livelihoods of women and children (literature review)",
        "year":  "2021",
        "geography":  "India (principally)",
        "exposure":  "Chronic and recurrent drought in rainâ€‘fed areas",
        "outcome":  "Undernutrition, food insecurity, health and livelihood outcomes",
        "priority":  "Medium",
        "step3":  "Maybe",
        "why":  "Indiaâ€‘focused review that synthesizes droughtâ€“undernutrition links and risk factors; useful for contextualizing ORs from specific studies but not itself a primary RRs.",
        "link":  "https://doi.org/10.1016/j.xxxx (see https://www.sciencedirect.com/science/article/abs/pii/S0190740920323318)  [sciencedirect](https://www.sciencedirect.com/science/article/abs/pii/S0190740920323318)"
    },
    {
        "cluster":  "Undernutrition_and_drought",
        "paper":  "Hunger, underâ€‘nutrition and food security in India (DFIDâ€‘supported review)",
        "year":  "2007â€“2008 (still cited in policy)",
        "geography":  "India",
        "exposure":  "Historical drought, monsoon variability, agricultural shocks",
        "outcome":  "Undernutrition prevalence, food insecurity",
        "priority":  "Medium",
        "step3":  "No (contextâ€‘only)",
        "why":  "Classic Indiaâ€‘focused foodâ€‘security/undernutrition review; informative for policy narrative but not for numeric RRs in EBOD.",
        "link":  "https://assets.publishing.service.gov.uk/media/.../CPRC-IIPA44.pdf  [assets.publishing.service.gov](https://assets.publishing.service.gov.uk/media/57a08ac540f0b652dd0008cc/CPRC-IIPA44.pdf)"
    },
    {
        "cluster":  "Undernutrition_and_drought",
        "paper":  "WHO India nutrition profile",
        "year":  "2019",
        "geography":  "India",
        "exposure":  "N/A (describes current burden)",
        "outcome":  "Undernutrition (stunting, wasting, underweight, overweight, anaemia)",
        "priority":  "Medium",
        "step3":  "Maybe",
        "why":  "Provides baseline prevalence and burden numbers for undernutrition that can be combined with climateâ€‘related RRs to estimate climateâ€‘attributable undernutrition.",
        "link":  "https://www.who.int/india/health-topics/nutrition  [who](https://www.who.int/india/health-topics/nutrition)"
    },
    {
        "cluster":  "Undernutrition_and_drought",
        "paper":  "India: Making children resilient to droughts (UN/PreventionWeb synthesis)",
        "year":  "2024â€“2025",
        "geography":  "India",
        "exposure":  "Historical and projected drought risk and foodâ€‘security factors",
        "outcome":  "Child undernutrition and resilience",
        "priority":  "Medium",
        "step3":  "No (contextâ€‘only)",
        "why":  "Excellent for policy context and resilience narratives; not for quantitative RRs or AFs.",
        "link":  "https://www.preventionweb.net/news/india-making-children-resilient-droughts  [preventionweb](https://www.preventionweb.net/news/india-making-children-resilient-droughts)"
    },
    {
        "cluster":  "Undernutrition_and_drought",
        "paper":  "Climate change and child nutrition in India â€“ â€œsilent crisisâ€ (policyâ€‘news)",
        "year":  "2025",
        "geography":  "India",
        "exposure":  "Climateâ€‘driven droughts, foodâ€‘price shocks, and foodâ€‘system instability",
        "outcome":  "Child undernutrition, food insecurity",
        "priority":  "Low",
        "step3":  "Maybe",
        "why":  "Useful qualitative evidence for stakeholder narrative; lacks explicit RRs but can support scenario descriptions.",
        "link":  "Example: https://www.facebook.com/TheWeekMag/posts/climate-change-impact-on-child-nutrition-in-india-is-creating-a-silent-crisis-as/  [facebook](https://www.facebook.com/TheWeekMag/posts/climate-change-impact-on-child-nutrition-in-india-is-creating-a-silent-crisis-as/1289120376593705/)"
    },
    {
        "cluster":  "Undernutrition_and_drought",
        "paper":  "Helping India combat persistently high rates of malnutrition (World Bank feature)",
        "year":  "2013",
        "geography":  "India",
        "exposure":  "Multiâ€‘year droughts, food price shocks, and weak social safety nets",
        "outcome":  "Chronic undernutrition",
        "priority":  "Medium",
        "step3":  "No (contextâ€‘only)",
        "why":  "Policyâ€‘oriented, not quantitative; helps justify the need for climateâ€‘linked nutrition programming but not EBOD inputs.",
        "link":  "https://www.worldbank.org/en/news/feature/2013/05/13/helping-india-combat-persistently-high-rates-of-malnutrition  [worldbank](https://www.worldbank.org/en/news/feature/2013/05/13/helping-india-combat-persistently-high-rates-of-malnutrition)"
    },
    {
        "cluster":  "Undernutrition_and_drought",
        "paper":  "UNICEF: Climate change and child nutrition (global context)",
        "year":  "2020s",
        "geography":  "Global, with India examples",
        "exposure":  "Droughts, waterâ€‘stress, and foodâ€‘system shocks",
        "outcome":  "Child undernutrition, dietary diversity, diarrhoeaâ€‘nutrition interaction",
        "priority":  "Medium",
        "step3":  "No (contextâ€‘only)",
        "why":  "Global context; useful for integrating droughtâ€“diarrhoeaâ€“undernutrition pathways into EBOD narrative.",
        "link":  "https://www.unicefusa.org/what-unicef-does/climate-change/nutrition  [unicefusa](https://www.unicefusa.org/what-unicef-does/climate-change/nutrition)"
    },
    {
        "cluster":  "Undernutrition_and_drought",
        "paper":  "Women and children in droughtâ€‘prone India (Indiaâ€‘specific vulnerability review)",
        "year":  "2021",
        "geography":  "India",
        "exposure":  "Drought in rainâ€‘fed, semiâ€‘arid regions (defined by rainfall regimes)",
        "outcome":  "Womenâ€™s and childrenâ€™s health, undernutrition, coping behaviour",
        "priority":  "Medium",
        "step3":  "Maybe",
        "why":  "Can be used to support genderâ€‘ and childâ€‘specific risk weights in EBOD, though not as a primary RRs source.",
        "link":  "(see The impact of drought on the health and livelihoods of women and children, 2021)  [sciencedirect](https://www.sciencedirect.com/science/article/abs/pii/S0190740920323318)"
    },
    {
        "cluster":  "Undernutrition_and_drought",
        "paper":  "Indiaâ€‘National Family Health Survey (NFHSâ€‘5, 2019â€“21) â€“ undernutrition and geography",
        "year":  "2021",
        "geography":  "India (stateâ€‘level)",
        "exposure":  "N/A (baseline prevalence)",
        "outcome":  "Child undernutrition (stunting, wasting, underweight)",
        "priority":  "Medium",
        "step3":  "Maybe",
        "why":  "Baseline data only; climateâ€‘related undernutrition RRs must be drawn from droughtâ€‘specific studies.",
        "link":  "NFHSâ€‘5 DHS report (see https://rchiips.org/NFHS/)"
    },
    {
        "cluster":  "Undernutrition_and_drought",
        "paper":  "Global droughtâ€“undernutrition metaâ€‘analysis (PNASâ€‘type study often cited in Indiaâ€‘policy)",
        "year":  "2010sâ€“2020s",
        "geography":  "Global, with Indiaâ€‘like LMICs",
        "exposure":  "Drought and rainfall anomaly",
        "outcome":  "Child undernutrition (stunting, wasting)",
        "priority":  "Medium",
        "step3":  "Yes",
        "why":  "Global pooled RRs for droughtâ†’undernutrition; can be used to bound Indiaâ€‘specific estimates where local ORs are sparse.",
        "link":  "See UNâ€‘linked droughtâ€‘nutrition syntheses embedded in PNASâ€‘style and UNâ€‘agency reports."
    }
];

